### PR TITLE
dep: support aws provider 4.x

### PR DESCRIPTION
**Pull request by naseemkullah**
## Summary

support version 4.x of aws tf provider

## How did you test this change?

vendored module into our repo 

## Issue

closes https://github.com/lacework/terraform-aws-iam-role/issues/26
and https://lacework.atlassian.net/browse/ALLY-881

### CODE REVIEW

**Comment by afiune** [comment]
@naseemkullah likewise here, we appreciate your contribution! Make it so 🙌🏽

**Comment by afiune** [comment]
Make it so 🙌🏽

**Comment by afiune** [comment]
Make it so 🙌🏽

**Review by afiune — APPROVED** [review]
tenor-225744005

**Comment by naseemkullah** [comment]
Would it be possible to cut a release?

**Pull request merged**
